//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delegator
    {
        public delegator()
        {
            this.client = new HashSet<client>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<int> agentId { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual ICollection<client> client { get; set; }
    }
}
