//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notes
    {
        public int id { get; set; }
        public string date { get; set; }
        public string note { get; set; }
        public Nullable<int> clientId { get; set; }
    
        public virtual client client { get; set; }
    }
}
