//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operations_supplier
    {
        public int id { get; set; }
        public Nullable<double> debtor { get; set; }
        public Nullable<double> creditor { get; set; }
        public Nullable<double> charg { get; set; }
        public string opType { get; set; }
        public string date { get; set; }
        public Nullable<int> supId { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
