//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchases
    {
        public int id { get; set; }
        public string date { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<int> shareehaId { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> total_after { get; set; }
        public Nullable<int> clientId { get; set; }
    
        public virtual client client { get; set; }
        public virtual shareha shareha { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
