//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_category_supplier
    {
        public sub_category_supplier()
        {
            this.supplier = new HashSet<supplier>();
        }
    
        public int id { get; set; }
        public string tasneef_name { get; set; }
        public Nullable<int> mainId { get; set; }
    
        public virtual main_category_supplier main_category_supplier { get; set; }
        public virtual ICollection<supplier> supplier { get; set; }
    }
}
