//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        public area()
        {
            this.agent = new HashSet<agent>();
            this.client = new HashSet<client>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> govId { get; set; }
    
        public virtual ICollection<agent> agent { get; set; }
        public virtual govern govern { get; set; }
        public virtual ICollection<client> client { get; set; }
    }
}
