//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_type
    {
        public client_type()
        {
            this.client = new HashSet<client>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<client> client { get; set; }
    }
}
