//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.client1 = new HashSet<client>();
            this.notes1 = new HashSet<notes>();
            this.operations_store = new HashSet<operations_store>();
            this.phones = new HashSet<phones>();
            this.purchases = new HashSet<purchases>();
            this.reportClientTahseel = new HashSet<reportClientTahseel>();
            this.sales = new HashSet<sales>();
        }
    
        public int id { get; set; }
        public string my_childs { get; set; }
        public string name { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> num_followers { get; set; }
        public string id_num { get; set; }
        public string date_of_birth { get; set; }
        public Nullable<int> client_type { get; set; }
        public string jop { get; set; }
        public string work_name { get; set; }
        public string work_place { get; set; }
        public string id_place { get; set; }
        public string stay_place { get; set; }
        public Nullable<int> stay_place_flat { get; set; }
        public Nullable<int> stay_place_floor { get; set; }
        public string stay_place_get { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<int> delegatorId { get; set; }
        public Nullable<int> available { get; set; }
        public Nullable<int> contract_state { get; set; }
        public string activation_date { get; set; }
        public string notes { get; set; }
        public Nullable<double> charge { get; set; }
        public string my_parents { get; set; }
        public Nullable<int> parentId { get; set; }
        public string contract_date { get; set; }
        public Nullable<double> MsgCharge { get; set; }
        public Nullable<int> done { get; set; }
    
        public virtual area area { get; set; }
        public virtual client_type client_type1 { get; set; }
        public virtual ICollection<client> client1 { get; set; }
        public virtual client client2 { get; set; }
        public virtual delegator delegator { get; set; }
        public virtual ICollection<notes> notes1 { get; set; }
        public virtual ICollection<operations_store> operations_store { get; set; }
        public virtual ICollection<phones> phones { get; set; }
        public virtual ICollection<purchases> purchases { get; set; }
        public virtual ICollection<reportClientTahseel> reportClientTahseel { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
