//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportClientTahseel
    {
        public int id { get; set; }
        public Nullable<int> cltId { get; set; }
        public Nullable<int> treasuryId { get; set; }
        public Nullable<double> charge { get; set; }
        public Nullable<double> diserved { get; set; }
        public string cltName { get; set; }
        public string cltAddress { get; set; }
        public string cltAreaName { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual client client { get; set; }
        public virtual stores stores { get; set; }
    }
}
