//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public sales()
        {
            this.operations_client = new HashSet<operations_client>();
        }
    
        public int id { get; set; }
        public string date { get; set; }
        public Nullable<int> serviceId { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> phoneId { get; set; }
        public Nullable<double> total { get; set; }
        public string notes { get; set; }
        public string time { get; set; }
        public string otherPhoneNum { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual ICollection<operations_client> operations_client { get; set; }
        public virtual phones phones { get; set; }
        public virtual services services { get; set; }
        public virtual client client { get; set; }
    }
}
