//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public services()
        {
            this.operations_client = new HashSet<operations_client>();
            this.sales = new HashSet<sales>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> sharehaId { get; set; }
        public Nullable<double> sellPrice { get; set; }
    
        public virtual ICollection<operations_client> operations_client { get; set; }
        public virtual ICollection<sales> sales { get; set; }
        public virtual shareha shareha { get; set; }
    }
}
