//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shareha
    {
        public shareha()
        {
            this.phones = new HashSet<phones>();
            this.purchases = new HashSet<purchases>();
            this.services = new HashSet<services>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> value { get; set; }
    
        public virtual ICollection<phones> phones { get; set; }
        public virtual ICollection<purchases> purchases { get; set; }
        public virtual ICollection<services> services { get; set; }
    }
}
