//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rody_sys.Areas.adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stores
    {
        public stores()
        {
            this.reportClientTahseel = new HashSet<reportClientTahseel>();
            this.operations_store = new HashSet<operations_store>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> value { get; set; }
    
        public virtual ICollection<reportClientTahseel> reportClientTahseel { get; set; }
        public virtual ICollection<operations_store> operations_store { get; set; }
    }
}
